const swaggerAutogen = require('swagger-autogen')();


const doc = {
  info: {
    version: '1.0.0',
    title: 'IDEA',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.'
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: [ 'http', 'https' ],
  consumes: [ 'application/json' ],
  produces: [ 'application/json' ],
  tags: [
    {
      'name': 'User',
      'description': 'Endpoints'
    }
  ],
  securityDefinitions: {
    'Bearer': {
      type: 'apiKey',
      in: 'header',       // can be "header", "query" or "cookie"
      name: 'Authorization',  // name of the header, query parameter or cookie
      description: 'token'
    }
  },
  definitions: {
    user: {
      'type': 'object',
      'properties': {
        'userId': {
          'type': 'Number'
        },
        'email': {
          'type': 'String'
        },
        'password': {
          'type': 'String'
        },
        'nickname': {
          'type': 'String'
        },
      }
    },
    post: {
      'type': 'object',
      'properties': {
        'postId': {
          'type': 'Number'
        },
        'title': {
          'type': 'String'
        },
        'nickname': {
          'type': 'String'
        },
        'spec': {
          'type': 'String'
        },
        'descr': {
          'type': 'String'
        },
        'image': {
          'type': 'String'
        },
        'place': {
          'type': 'Number'
        },
      }
    },
    comment: {
      'type': 'object',
      'properties': {
        'commentId': {
          'type': 'Number'
        },
        'commentTime': {
          'type': 'String'
        },
        'nickname': {
          'type': 'String'
        },
        'comment': {
          'type': 'String'
        },
        'upperPost': {
          'type': 'Number'
        },
      }
    },
    wish: {
      'type': 'object',
      'properties': {
        'Id': {
          'type': 'Number'
        },
        'userId': {
          'type': 'Number'
        },
        'postId': {
          'type': 'Number'
        },
      }
    },
  }
};

const outputFile = './swagger_output.json';
const endpointsFiles = [ './routers/*.js', './app.js' ];

swaggerAutogen(outputFile, endpointsFiles, doc);